In [1]:
import pandas as pd
import numpy as np # importing neccesary library

In [2]:
df = pd.read_csv(r"C:\Users\user\Downloads\openaq_delhi.csv",sep=";",error_bad_lines=False)
#reading dataset

C:\Users\user\AppData\Local\Temp\ipykernel_9796\2083449281.py:1: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv(r"C:\Users\user\Downloads\openaq_delhi.csv",sep=";",error_bad_lines=False)

In [3]:
df.head()

,Country Code,City,Location,Coordinates,Pollutant,Source Name,Unit,Value,Last Updated,Country Label
0,IN,Delhi,"Okhla Phase-2, Delhi - DPCC",NaN,O3,data.gov.in,µg/m³,5.0,2022-03-25T05:00:00+05:30,India
1,IN,Delhi,"Sonia Vihar, Delhi - DPCC",NaN,PM2.5,data.gov.in,µg/m³,183.0,2022-03-25T05:00:00+05:30,India
2,IN,Delhi,"Major Dhyan Chand National Stadium, Delhi - DPCC",NaN,NO2,data.gov.in,µg/m³,53.0,2022-03-25T05:00:00+05:30,India
3,IN,Delhi,"Najafgarh, Delhi - DPCC",NaN,SO2,data.gov.in,µg/m³,5.0,2022-03-25T05:00:00+05:30,India
4,IN,Delhi,"Aya Nagar, Delhi - IMD",NaN,NO2,data.gov.in,µg/m³,25.0,2022-03-25T05:00:00+05:30,India

In [4]:
df.isnull().value_counts()

Country Code  City   Location  Coordinates  Pollutant  Source Name  Unit   Value  Last Updated  Country Label
False         False  False     False        False      False        False  False  False         False            410
                               True         False      False        False  False  False         False            254
dtype: int64

In [5]:
df.isnull().sum()
#reviewing null values

Country Code       0
City               0
Location           0
Coordinates      254
Pollutant          0
Source Name        0
Unit               0
Value              0
Last Updated       0
Country Label      0
dtype: int64

In [6]:
df.shape

(664, 10)

# Using sklearn Random Forest regressor

In [7]:
df.sample(5)

,Country Code,City,Location,Coordinates,Pollutant,Source Name,Unit,Value,Last Updated,Country Label
371,IN,Delhi,"Ashok Vihar, Delhi - DPCC","28.6957202, 77.1812947",PM10,caaqm,µg/m³,366.00,2018-05-12T11:30:00+05:30,India
169,IN,Delhi,"Alipur, Delhi - DPCC","28.815329, 77.15301",O3,caaqm,µg/m³,7.50,2022-10-31T06:00:00+05:30,India
612,IN,Delhi,"CRRI Mathura Road, Delhi - IMD",NaN,CO,CPCB,µg/m³,1600.00,2018-02-22T04:45:00+05:30,India
358,IN,Delhi,"Wazirpur, Delhi - DPCC","28.701616, 77.164238",O3,caaqm,µg/m³,175.10,2018-05-10T17:00:00+05:30,India
547,IN,Delhi,IGI Airport,"28.56, 77.094",NO2,CPCB,µg/m³,39.18,2015-07-10T12:00:00+05:30,India

In [8]:
def unicolumns(col):
    print(f'Details of particular columns {col} is : {df[col].unique()}')

In [9]:
def value_count(col):
    print(f'count of Unique value of columns {col} is : {df[col].value_counts()}')

In [10]:
df.columns

Index(['Country Code', 'City', 'Location', 'Coordinates', 'Pollutant',
       'Source Name', 'Unit', 'Value', 'Last Updated', 'Country Label'],
      dtype='object')

In [11]:
for col in df.columns:
    unicolumns(col)
    print('-'*70)

Details of particular columns Country Code is : ['IN']
----------------------------------------------------------------------
Details of particular columns City is : ['Delhi']
----------------------------------------------------------------------
Details of particular columns Location is : ['Okhla Phase-2, Delhi - DPCC' 'Sonia Vihar, Delhi - DPCC'
 'Major Dhyan Chand National Stadium, Delhi - DPCC'
 'Najafgarh, Delhi - DPCC' 'Aya Nagar, Delhi - IMD'
 'Burari Crossing, Delhi - IMD' 'CRRI Mathura Road, Delhi - IMD'
 'R K Puram, Delhi - DPCC' 'Shadipur, Delhi - CPCB'
 'Nehru Nagar, Delhi - DPCC' 'Narela, Delhi - DPCC'
 'Dwarka-Sector 8, Delhi - DPCC'
 'Delhi Technological University, Delhi - CPCB'
 'Income Tax Office, Delhi - CPCB' 'North Campus, Delhi - IMD'
 'Anand Vihar, Delhi - DPCC' 'Lodhi Road, Delhi - IMD'
 'US Diplomatic Post: New Delhi' 'North Campus, DU, Delhi - IMD'
 'ITO, Delhi - CPCB' 'Pusa, Delhi - DPCC' 'Vivek Vihar, Delhi - DPCC'
 'Sri Aurobindo Marg, Delhi - DPCC'
 'Jawaharlal Nehru Stadium, Delhi - DPCC' 'Jahangirpuri, Delhi - DPCC'
 'Dr. Karni Singh Shooting Range, Delhi - DPCC'
 'Chandni Chowk, Delhi - IITM' 'Punjabi Bagh, Delhi - DPCC'
 'Patparganj, Delhi - DPCC' 'DTU, Delhi - CPCB' 'Pusa, Delhi - IMD'
 'East Arjun Nagar, Delhi - CPCB' 'Ashok Vihar, Delhi - DPCC'
 'IGI Airport Terminal-3, Delhi - IMD' 'Mandir Marg, Delhi - DPCC'
 'Civil Lines' 'Pusa, New Delhi - IMD' 'Rohini, Delhi - DPCC'
 'R K Puram, New Delhi - DPCC' 'Sirifort, Delhi - CPCB'
 'IGI Airport (T3), Delhi - IMD' 'Alipur, Delhi - DPCC'
 'IHBAS, Delhi - CPCB' 'IGI Airport' 'Wazirpur, Delhi - DPCC'
 'Mandir Marg, New Delhi - DPCC' 'NSIT Dwarka, Delhi - CPCB'
 'Mundka, Delhi - DPCC' 'Lodhi Road, Delhi - IITM'
 'IHBAS, Dilshad Garden, Delhi - CPCB' 'Bawana, Delhi - DPCC'
 'IHBAS, Dilshad Garden,New Delhi - CPCB' 'Siri Fort' 'Pusa2 IMD'
 'East Arjun Nagar' 'East Arjun Nagar-Delhi CPCB']
----------------------------------------------------------------------
Details of particular columns Coordinates is : [nan '28.5639543, 77.2587868' '28.8446874, 77.0332666'
 '28.5206826, 76.8023871' '28.744, 77.12' '28.6235, 77.2494'
 '28.6508, 77.3152' '28.63576, 77.22445' '28.6573814, 77.1585447'
 '28.628624, 77.24106' '28.4706914, 77.1099364' '28.639645, 77.146262'
 '28.672342, 77.31526' '28.563262, 77.186937' '28.530785, 77.271255'
 '28.531346, 77.190156' '28.822836, 77.101981' '28.5918245, 77.2273074'
 '28.58028, 77.233829' '28.73282, 77.170633' '28.498571, 77.26484'
 '28.656756, 77.227234' '28.646835, 77.316032' '28.6556017, 77.2859318'
 '28.6316945, 77.2494387' '28.5366411, 77.2664587'
 '28.6957202, 77.1812947' '28.6517, 77.1581' '28.6341, 77.2005'
 '28.6787, 77.2262' '28.610304, 77.0996943' '28.6670856, 77.1301247'
 '28.7407056, 77.0577492' '28.7258373, 77.1605631' '28.67795, 77.29868'
 '28.5646102, 77.1670103' '28.6125027, 77.2351994' '28.5648, 77.1744'
 '28.5504249, 77.2159377' '28.5512005, 77.2735737' '28.611281, 77.237738'
 '28.732528, 77.11992' '28.5627763, 77.1180053' '28.7256504, 77.2011573'
 '28.5828503, 77.2321778' '28.4997315, 77.2649067' '28.6821, 77.305'
 '28.56, 77.094' '28.699793, 77.165453' '28.6372688, 77.2005604'
 '28.60909, 77.0325413' '28.6514781, 77.1473105' '28.5710274, 77.0719006'
 '28.710508, 77.249485' '28.684678, 77.076574' '28.815329, 77.15301'
 '28.6683, 77.1167' '28.6811736, 77.3025234' '28.636429, 77.201067'
 '28.56789, 77.250515' '28.695381, 77.181665' '28.701616, 77.164238'
 '28.570173, 76.933762' '28.647622, 77.315809' '28.674045, 77.131023'
 '28.588333, 77.221667' '28.5108561, 76.7093948' '28.6802747, 77.2011573'
 '28.7500499, 77.1112615' '28.7762, 77.051074' '28.6687803, 77.3130982'
 '28.598096, 77.189066' '28.623763, 77.287209' '28.6310495, 77.2846218'
 '28.591, 77.05' '28.655935, 77.294904']
----------------------------------------------------------------------
Details of particular columns Pollutant is : ['O3' 'PM2.5' 'NO2' 'SO2' 'PM10' 'CO']
----------------------------------------------------------------------
Details of particular columns Source Name is : ['data.gov.in' 'caaqm' 'CPCB' 'StateAir_NewDelhi']
----------------------------------------------------------------------
Details of particular columns Unit is : ['µg/m³' 'ppm']
----------------------------------------------------------------------
Details of particular columns Value is : [5.0000e+00 1.8300e+02 5.3000e+01 2.5000e+01 1.8000e+01 2.8700e+02
 8.0000e+04 1.3000e+01 2.2200e+02 2.1400e+02 1.7300e+02 2.3100e+01
 4.5100e+02 2.2400e+02 5.8280e+01 1.7870e+01 1.5262e+02 6.1000e+01
 1.4590e+01 8.4000e+00 2.5020e+01 2.9900e+02 3.6100e+01 2.1100e+01
 2.0000e+03 6.7000e+00 3.8000e+00 6.6600e+01 2.2000e+00 1.5540e+02
 1.2400e+01 7.0000e+02 3.9900e+02 2.1000e+00 1.3200e+00 5.6000e+04
 1.5000e+01 3.3000e+01 8.0000e+00 2.4000e+02 3.0000e+00 1.0500e+05
 4.0000e+00 1.5200e+02 1.8500e+02 2.4000e+00 9.5950e+01 2.2170e+01
 7.4000e+01 3.6900e+01 1.8790e+02 1.3430e+01 2.8986e+02 1.4470e+01
 4.8990e+01 2.2000e+01 1.2000e+01 9.4000e+01 9.4000e+04 2.3500e+02
 2.2700e+02 5.0370e+01 4.3100e+02 1.1000e+02 3.4400e+01 1.3900e+02
 6.0000e-01 8.1400e+01 1.0000e-01 3.1700e+00 3.3900e+02 9.7900e+02
 2.8310e+01 1.0000e+00 2.3800e+02 7.3200e+00 0.0000e+00 1.9600e+02
 6.7000e+01 2.4300e+02 1.4100e+05 3.7800e+02 9.0000e+02 2.1300e+02
 1.8400e+01 2.9000e+01 4.0300e+01 1.1900e+01 6.7000e+02 9.1000e+02
 3.5200e+00 3.3700e+02 2.4800e+02 2.6000e+01 2.0000e+00 2.6500e+02
 5.2000e+04 5.0000e+01 6.4200e+01 6.2000e+01 2.7100e+02 2.6000e+00
 1.9750e+01 2.0840e+02 1.3920e+02 3.1000e+00 9.0000e+00 6.0000e+00
 3.2800e+01 6.5900e+01 3.4100e+01 6.3000e+00 1.7900e+02 4.3000e+01
 1.4000e+01 1.8100e+02 7.0000e+00 8.7000e+00 2.0100e+02 3.2200e+02
 9.2000e+00 2.7680e+01 1.4760e+02 1.1420e+01 1.7500e+03 1.5800e+01
 1.7400e+03 8.8700e+01 8.2500e+01 3.0000e+02 3.9200e+02 6.0000e+02
 5.0000e-01 9.0000e+04 2.6400e+02 6.5000e+04 3.0000e+01 2.5800e+01
 5.4400e+01 2.5100e+02 6.4200e+00 8.7000e+02 3.2731e+02 1.4000e+03
 4.2100e+02 7.1500e+01 2.8000e+02 5.0400e+02 7.5000e+00 1.7150e+01
 5.4000e+04 1.1000e+01 1.6000e+01 9.5000e+01 1.2200e+05 3.2000e+01
 2.8000e+03 8.2000e+00 2.5000e+02 2.9600e+02 1.5500e+02 1.0440e+02
 1.9781e+02 1.3000e+03 1.5000e+03 4.4700e+01 8.3390e+02 3.7900e+02
 1.5000e+00 4.2300e+02 3.0000e+03 6.8000e+00 4.6000e+00 2.0400e+02
 2.4200e+02 2.5800e+02 2.8700e+01 2.3300e+02 1.9100e+01 4.1600e+02
 3.6189e+02 2.4100e+02 1.8800e+02 8.9700e+01 1.2600e+01 2.2800e+01
 4.2900e+02 3.5400e+02 6.8000e+01 1.7400e+02 2.8000e+01 1.4300e+02
 1.7000e+01 2.0200e+02 2.3700e+02 3.6100e+02 1.7400e+01 1.8000e+02
 2.0300e+01 3.8200e+01 2.5000e+03 1.2644e+02 1.5610e+01 1.1090e+01
 1.4300e+01 4.2700e+02 2.3200e+02 2.5400e+01 1.0756e+02 5.4700e+01
 1.0100e+02 1.7700e+02 8.9000e+04 1.9000e+02 1.7530e+01 1.4100e+01
 1.0500e+02 3.5600e+02 1.3210e+02 5.6820e+01 1.8000e+03 1.4000e+00
 2.5600e+02 3.1000e+02 5.1000e+00 9.0000e-01 2.7300e+02 5.9000e+01
 1.2700e+02 4.2000e+04 7.3000e+04 5.7000e+04 1.8200e+02 1.4500e+03
 1.4900e+02 1.2000e+03 2.6900e+01 8.7400e+01 3.1700e+01 2.1400e+03
 1.6888e+02 8.6000e+02 1.7000e+00 2.3900e+02 1.3380e+01 7.8900e+01
 2.5500e+02 6.9000e+04 2.1000e+01 2.1200e+02 1.8900e+02 1.3170e+02
 1.5500e+01 9.2900e+01 6.9000e+01 1.0870e-02 3.1700e+02 3.6000e+00
 4.0300e+02 2.9700e+01 2.1700e+01 2.1700e+02 9.0000e+01 2.1500e+02
 3.5020e+01 1.8800e+01 1.9870e+02 1.3400e+02 1.2430e+01 2.4100e+03
 3.1910e+01 3.2700e+02 8.6000e+00 3.4900e+02 2.0000e-01 9.7500e+01
 3.6630e+01 2.4400e+01 3.0970e+02 5.7000e+00 2.6600e+02 8.0000e+02
 1.4500e+01 2.2000e+03 5.9240e+02 1.9000e+01 6.4000e+04 1.6200e+02
 9.9000e+00 1.7510e+02 1.3140e+02 9.2740e+01 1.6520e+01 8.4000e+01
 1.8600e+02 2.0000e+01 1.1160e+01 1.6930e+02 2.0050e+02 3.6600e+02
 2.8380e+01 4.3000e+03 7.5000e+03 3.0338e+02 1.0948e+02 5.0800e+00
 1.9200e+03 1.9000e+03 2.9500e+01 9.6000e+02 7.0000e+03 2.4500e+02
 4.2300e+01 3.6500e+01 2.6800e+02 9.0100e+01 9.1000e+01 2.9500e+02
 1.9400e+03 5.0000e+02 2.9000e+04 8.2000e+04 2.3000e+02 3.0700e+02
 3.2000e+04 1.0578e+02 1.2370e+01 2.3000e+03 4.7600e+02 3.5300e+02
 1.5000e+02 2.4900e+02 4.6900e+02 1.0500e+00 6.2000e+04 5.0000e+04
 3.2400e+01 5.4060e+01 7.3810e+01 6.8407e+02 3.4582e+02 4.9300e+02
 3.0900e+02 4.4900e+02 1.5702e+02 5.6000e+01 4.2000e+01 7.7000e+00
 1.8100e+01 2.3000e+00 1.0410e+02 1.2143e+02 1.3900e+03 1.0300e+01
 4.6400e+01 7.6000e+00 4.5100e+01 4.7960e+01 8.8000e+04 6.4000e+01
 6.9000e+00 1.7000e+03 4.0000e+02 5.9000e+00 8.3100e+01 1.7600e+03
 3.4600e+01 2.4600e+02 4.1000e+01 1.6400e+02 8.6000e+01 7.9000e+04
 1.1290e+01 3.1650e+01 1.3190e+02 6.2200e+01 2.5500e+01 8.1000e+02
 1.9330e+01 3.0600e+02 2.0825e+02 8.9000e+00 6.1660e+01 3.8990e+01
 3.4800e+01 2.8300e+02 6.4290e+01 8.5000e+04 4.9000e+01 5.8000e+04
 1.1700e+02 1.9700e+02 6.5000e+01 2.0900e+02 7.5000e+01 4.0700e+02
 2.2960e+02 6.2000e+00 2.4100e+01 1.4100e+03 2.4707e+02 1.4824e+02
 9.7290e+01 2.4000e+01 3.5760e+02 2.8340e+01 9.1000e+00 1.0000e+01
 1.1400e+02 2.6100e+02 8.4000e+04 2.4700e+02 1.7600e+01 7.2000e+00
 1.5100e+02 3.1200e+02 2.1940e+02 2.3300e+03 3.9180e+01 5.7900e+01
 2.2472e+02 2.2800e+02 2.1000e+02 3.9000e+00 2.1900e+02 1.6100e+02
 9.6000e+01 2.9870e+01 2.3400e+01 1.0510e+02 2.0670e+01 6.2000e+02
 1.3700e+00 2.1110e+01 3.7800e+03 3.7900e+03 1.7800e+01 4.4900e+01
 1.0000e+02 1.1000e+05 1.3800e+02 1.7500e+01 1.1120e+02 1.3200e+02
 1.2900e+02 3.9640e+01 3.9070e+01 2.0800e+02 2.3544e+02 3.2470e+01
 3.6400e+02 4.2000e+00 3.1300e+02 3.4500e+02 6.9600e+00 1.2300e+03
 2.0700e+02 3.8000e+04 2.0000e+02 1.3600e+02 7.7000e+04 1.3930e+02
 1.0800e+01 1.6000e+03 5.6900e+01 5.5449e+02 3.2000e+03 5.2000e+00
 2.8200e+02 6.9800e+00 1.0200e+05 1.0400e+02 7.2000e+01 4.0000e+01
 1.8110e+02 9.9000e+01 3.9589e+02 7.7600e+01 6.3100e+01 8.0200e+00
 2.7500e+02 6.0000e+01 2.9000e+02 1.5593e+02 8.9100e+01 4.0800e+01
 9.9500e+01 2.7700e+02 6.1000e+00 1.5200e+01 7.1000e+02 1.9800e+02
 3.3800e+02 5.5000e+01 7.9030e+01 9.5330e+01 1.8600e+03]
----------------------------------------------------------------------
Details of particular columns Last Updated is : ['2022-03-25T05:00:00+05:30' '2018-05-12T11:30:00+05:30'
 '2018-05-12T10:30:00+05:30' '2018-02-22T09:30:00+05:30'
 '2018-02-22T09:15:00+05:30' '2018-02-22T04:30:00+05:30'
 '2018-01-23T10:00:00+05:30' '2018-02-22T02:30:00+05:30'
 '2023-03-01T05:00:00+05:30' '2022-06-22T07:45:00+05:30'
 '2022-10-31T07:15:00+05:30' '2022-10-31T06:45:00+05:30'
 '2022-10-31T06:15:00+05:30' '2022-10-30T16:45:00+05:30'
 '2022-10-16T15:45:00+05:30' '2022-10-31T06:00:00+05:30'
 '2022-08-02T16:00:00+05:30' '2021-09-20T13:15:00+05:30'
 '2020-02-10T08:30:00+05:30' '2020-01-20T12:45:00+05:30'
 '2018-05-13T15:30:00+05:30' '2018-05-12T10:00:00+05:30'
 '2018-02-22T08:15:00+05:30' '2018-02-22T04:45:00+05:30'
 '2018-02-22T02:45:00+05:30' '2015-07-10T13:45:00+05:30'
 '2018-05-14T07:30:00+05:30' '2018-05-13T17:00:00+05:30'
 '2018-05-12T12:00:00+05:30' '2018-05-11T17:15:00+05:30'
 '2018-05-07T01:00:00+05:30' '2022-10-16T21:30:00+05:30'
 '2022-08-03T16:30:00+05:30' '2018-05-10T15:00:00+05:30'
 '2018-05-12T10:15:00+05:30' '2018-05-09T16:30:00+05:30'
 '2015-07-10T12:00:00+05:30' '2021-09-20T11:15:00+05:30'
 '2018-05-11T18:00:00+05:30' '2018-05-10T13:00:00+05:30'
 '2022-10-31T07:30:00+05:30' '2022-10-16T20:45:00+05:30'
 '2018-02-21T12:30:00+05:30' '2018-05-10T17:00:00+05:30'
 '2022-10-16T19:45:00+05:30' '2022-08-02T15:00:00+05:30'
 '2018-04-28T20:00:00+05:30' '2016-03-21T20:15:00+05:30'
 '2018-05-10T14:30:00+05:30' '2015-04-09T11:30:00+05:30'
 '2017-11-28T16:00:00+05:30' '2017-11-07T13:15:00+05:30'
 '2016-11-09T22:00:00+05:30' '2018-05-12T11:00:00+05:30'
 '2016-04-05T14:30:00+05:30' '2022-10-16T20:30:00+05:30'
 '2022-10-31T04:30:00+05:30' '2018-02-22T02:15:00+05:30'
 '2018-02-21T13:00:00+05:30' '2022-01-26T12:30:00+05:30'
 '2022-10-16T19:15:00+05:30' '2022-10-31T03:45:00+05:30'
 '2022-10-31T05:45:00+05:30' '2018-02-21T12:00:00+05:30'
 '2018-02-21T22:15:00+05:30' '2022-10-31T02:00:00+05:30'
 '2018-02-22T03:30:00+05:30' '2018-05-08T12:00:00+05:30'
 '2022-10-31T05:30:00+05:30' '2022-10-31T04:15:00+05:30'
 '2018-01-24T15:00:00+05:30']
----------------------------------------------------------------------
Details of particular columns Country Label is : ['India']
----------------------------------------------------------------------

In [12]:
df.drop(['Country Code','City','Country Label'],axis=1, inplace = True)
#droping coulumns who don't have any significant for finding null values

In [13]:
df.head()

,Location,Coordinates,Pollutant,Source Name,Unit,Value,Last Updated
0,"Okhla Phase-2, Delhi - DPCC",NaN,O3,data.gov.in,µg/m³,5.0,2022-03-25T05:00:00+05:30
1,"Sonia Vihar, Delhi - DPCC",NaN,PM2.5,data.gov.in,µg/m³,183.0,2022-03-25T05:00:00+05:30
2,"Major Dhyan Chand National Stadium, Delhi - DPCC",NaN,NO2,data.gov.in,µg/m³,53.0,2022-03-25T05:00:00+05:30
3,"Najafgarh, Delhi - DPCC",NaN,SO2,data.gov.in,µg/m³,5.0,2022-03-25T05:00:00+05:30
4,"Aya Nagar, Delhi - IMD",NaN,NO2,data.gov.in,µg/m³,25.0,2022-03-25T05:00:00+05:30

In [14]:
def number_unicolumns(col):
    print(f'Details of particular columns unique value {col} is : {df[col].nunique()}')

In [15]:
for col in df.columns:
    number_unicolumns(col)
    print('-'*70)

Details of particular columns unique value Location is : 56
----------------------------------------------------------------------
Details of particular columns unique value Coordinates is : 75
----------------------------------------------------------------------
Details of particular columns unique value Pollutant is : 6
----------------------------------------------------------------------
Details of particular columns unique value Source Name is : 4
----------------------------------------------------------------------
Details of particular columns unique value Unit is : 2
----------------------------------------------------------------------
Details of particular columns unique value Value is : 497
----------------------------------------------------------------------
Details of particular columns unique value Last Updated is : 71
----------------------------------------------------------------------

In [16]:
df.dtypes

Location         object
Coordinates      object
Pollutant        object
Source Name      object
Unit             object
Value           float64
Last Updated     object
dtype: object

1 ppm = 1 g/m³
1 µg/m³ = 10^(-6) ppm

In [17]:
df[df['Unit'] == 'ppm']

,Location,Coordinates,Pollutant,Source Name,Unit,Value,Last Updated
310,"North Campus, DU, Delhi - IMD","28.6573814, 77.1585447",O3,caaqm,ppm,0.01087,2022-10-31T07:30:00+05:30

In [18]:
df.head()

,Location,Coordinates,Pollutant,Source Name,Unit,Value,Last Updated
0,"Okhla Phase-2, Delhi - DPCC",NaN,O3,data.gov.in,µg/m³,5.0,2022-03-25T05:00:00+05:30
1,"Sonia Vihar, Delhi - DPCC",NaN,PM2.5,data.gov.in,µg/m³,183.0,2022-03-25T05:00:00+05:30
2,"Major Dhyan Chand National Stadium, Delhi - DPCC",NaN,NO2,data.gov.in,µg/m³,53.0,2022-03-25T05:00:00+05:30
3,"Najafgarh, Delhi - DPCC",NaN,SO2,data.gov.in,µg/m³,5.0,2022-03-25T05:00:00+05:30
4,"Aya Nagar, Delhi - IMD",NaN,NO2,data.gov.in,µg/m³,25.0,2022-03-25T05:00:00+05:30

In [19]:
df.loc[df.Unit == 'ppm', 'Value'] = 10870
#changing unit in only one scale

In [20]:
df[df.Unit == 'ppm']

,Location,Coordinates,Pollutant,Source Name,Unit,Value,Last Updated
310,"North Campus, DU, Delhi - IMD","28.6573814, 77.1585447",O3,caaqm,ppm,10870.0,2022-10-31T07:30:00+05:30

In [21]:
df.drop(['Unit','Last Updated'],axis=1, inplace = True)

In [22]:
df.head()

,Location,Coordinates,Pollutant,Source Name,Value
0,"Okhla Phase-2, Delhi - DPCC",NaN,O3,data.gov.in,5.0
1,"Sonia Vihar, Delhi - DPCC",NaN,PM2.5,data.gov.in,183.0
2,"Major Dhyan Chand National Stadium, Delhi - DPCC",NaN,NO2,data.gov.in,53.0
3,"Najafgarh, Delhi - DPCC",NaN,SO2,data.gov.in,5.0
4,"Aya Nagar, Delhi - IMD",NaN,NO2,data.gov.in,25.0

In [23]:
df['Pollutant'].nunique()

6

In [24]:
df['Location'].nunique()

56

In [25]:
df['Source Name'].nunique()

4

In [26]:
df.head()

,Location,Coordinates,Pollutant,Source Name,Value
0,"Okhla Phase-2, Delhi - DPCC",NaN,O3,data.gov.in,5.0
1,"Sonia Vihar, Delhi - DPCC",NaN,PM2.5,data.gov.in,183.0
2,"Major Dhyan Chand National Stadium, Delhi - DPCC",NaN,NO2,data.gov.in,53.0
3,"Najafgarh, Delhi - DPCC",NaN,SO2,data.gov.in,5.0
4,"Aya Nagar, Delhi - IMD",NaN,NO2,data.gov.in,25.0

In [27]:
df.shape

(664, 5)

In [28]:
new_df = pd.get_dummies(df, columns = ['Location','Pollutant','Source Name'], drop_first = True)
#applying one hot encoding

In [29]:
new_df

,Coordinates,Value,"Location_Anand Vihar, Delhi - DPCC","Location_Ashok Vihar, Delhi - DPCC","Location_Aya Nagar, Delhi - IMD","Location_Bawana, Delhi - DPCC","Location_Burari Crossing, Delhi - IMD","Location_CRRI Mathura Road, Delhi - IMD","Location_Chandni Chowk, Delhi - IITM",Location_Civil Lines,...,"Location_Vivek Vihar, Delhi - DPCC","Location_Wazirpur, Delhi - DPCC",Pollutant_NO2,Pollutant_O3,Pollutant_PM10,Pollutant_PM2.5,Pollutant_SO2,Source Name_StateAir_NewDelhi,Source Name_caaqm,Source Name_data.gov.in
0,NaN,5.00,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
1,NaN,183.00,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
2,NaN,53.00,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
3,NaN,5.00,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
4,NaN,25.00,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
659,"28.6310495, 77.2846218",10.30,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
660,"28.6310495, 77.2846218",67.00,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
661,NaN,79.03,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
662,"28.5648, 77.1744",95.33,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
663,NaN,1860.00,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [30]:
df1 = new_df[new_df.Coordinates.isnull()]

In [31]:
df1

,Coordinates,Value,"Location_Anand Vihar, Delhi - DPCC","Location_Ashok Vihar, Delhi - DPCC","Location_Aya Nagar, Delhi - IMD","Location_Bawana, Delhi - DPCC","Location_Burari Crossing, Delhi - IMD","Location_CRRI Mathura Road, Delhi - IMD","Location_Chandni Chowk, Delhi - IITM",Location_Civil Lines,...,"Location_Vivek Vihar, Delhi - DPCC","Location_Wazirpur, Delhi - DPCC",Pollutant_NO2,Pollutant_O3,Pollutant_PM10,Pollutant_PM2.5,Pollutant_SO2,Source Name_StateAir_NewDelhi,Source Name_caaqm,Source Name_data.gov.in
0,NaN,5.00,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
1,NaN,183.00,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
2,NaN,53.00,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
3,NaN,5.00,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
4,NaN,25.00,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
656,NaN,198.00,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
657,NaN,338.00,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
658,NaN,55.00,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
661,NaN,79.03,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
663,NaN,1860.00,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [32]:
df2 = new_df[new_df.Coordinates.notnull()]

In [33]:
df2.head()

,Coordinates,Value,"Location_Anand Vihar, Delhi - DPCC","Location_Ashok Vihar, Delhi - DPCC","Location_Aya Nagar, Delhi - IMD","Location_Bawana, Delhi - DPCC","Location_Burari Crossing, Delhi - IMD","Location_CRRI Mathura Road, Delhi - IMD","Location_Chandni Chowk, Delhi - IITM",Location_Civil Lines,...,"Location_Vivek Vihar, Delhi - DPCC","Location_Wazirpur, Delhi - DPCC",Pollutant_NO2,Pollutant_O3,Pollutant_PM10,Pollutant_PM2.5,Pollutant_SO2,Source Name_StateAir_NewDelhi,Source Name_caaqm,Source Name_data.gov.in
10,"28.5639543, 77.2587868",214.0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
11,"28.8446874, 77.0332666",173.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
12,"28.5206826, 76.8023871",23.1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
13,"28.744, 77.12",451.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
14,"28.6235, 77.2494",224.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [34]:
splitdf = df2['Coordinates'].str.split(',', n=1, expand = True)

# spliting coordinate value in (x,y)

In [35]:
splitdf

              0            1
10   28.5639543   77.2587868
11   28.8446874   77.0332666
12   28.5206826   76.8023871
13       28.744        77.12
14      28.6235      77.2494
..          ...          ...
649   28.684678    77.076574
650   28.656756    77.227234
659  28.6310495   77.2846218
660  28.6310495   77.2846218
662     28.5648      77.1744

[410 rows x 2 columns]

In [36]:
df2['X_cor'] = splitdf[0]
df2['Y_cor'] = splitdf[1]

C:\Users\user\AppData\Local\Temp\ipykernel_9796\2822549928.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['X_cor'] = splitdf[0]
C:\Users\user\AppData\Local\Temp\ipykernel_9796\2822549928.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Y_cor'] = splitdf[1]

In [37]:
df2.head()
#making final df which have x and y coordinate

,Coordinates,Value,"Location_Anand Vihar, Delhi - DPCC","Location_Ashok Vihar, Delhi - DPCC","Location_Aya Nagar, Delhi - IMD","Location_Bawana, Delhi - DPCC","Location_Burari Crossing, Delhi - IMD","Location_CRRI Mathura Road, Delhi - IMD","Location_Chandni Chowk, Delhi - IITM",Location_Civil Lines,...,Pollutant_NO2,Pollutant_O3,Pollutant_PM10,Pollutant_PM2.5,Pollutant_SO2,Source Name_StateAir_NewDelhi,Source Name_caaqm,Source Name_data.gov.in,X_cor,Y_cor
10,"28.5639543, 77.2587868",214.0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,28.5639543,77.2587868
11,"28.8446874, 77.0332666",173.0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,28.8446874,77.0332666
12,"28.5206826, 76.8023871",23.1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,28.5206826,76.8023871
13,"28.744, 77.12",451.0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,28.744,77.12
14,"28.6235, 77.2494",224.0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,28.6235,77.2494

In [38]:
df2.drop(['Coordinates'],axis=1, inplace = True)

C:\Users\user\AppData\Local\Temp\ipykernel_9796\2012777577.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop(['Coordinates'],axis=1, inplace = True)

In [39]:
df2.head()

,Value,"Location_Anand Vihar, Delhi - DPCC","Location_Ashok Vihar, Delhi - DPCC","Location_Aya Nagar, Delhi - IMD","Location_Bawana, Delhi - DPCC","Location_Burari Crossing, Delhi - IMD","Location_CRRI Mathura Road, Delhi - IMD","Location_Chandni Chowk, Delhi - IITM",Location_Civil Lines,"Location_DTU, Delhi - CPCB",...,Pollutant_NO2,Pollutant_O3,Pollutant_PM10,Pollutant_PM2.5,Pollutant_SO2,Source Name_StateAir_NewDelhi,Source Name_caaqm,Source Name_data.gov.in,X_cor,Y_cor
10,214.0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,28.5639543,77.2587868
11,173.0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,28.8446874,77.0332666
12,23.1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,28.5206826,76.8023871
13,451.0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,28.744,77.12
14,224.0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,28.6235,77.2494

In [40]:
X_train = df2.drop(['X_cor','Y_cor'],axis=1)
# training dataset

In [41]:
df2.head()

,Value,"Location_Anand Vihar, Delhi - DPCC","Location_Ashok Vihar, Delhi - DPCC","Location_Aya Nagar, Delhi - IMD","Location_Bawana, Delhi - DPCC","Location_Burari Crossing, Delhi - IMD","Location_CRRI Mathura Road, Delhi - IMD","Location_Chandni Chowk, Delhi - IITM",Location_Civil Lines,"Location_DTU, Delhi - CPCB",...,Pollutant_NO2,Pollutant_O3,Pollutant_PM10,Pollutant_PM2.5,Pollutant_SO2,Source Name_StateAir_NewDelhi,Source Name_caaqm,Source Name_data.gov.in,X_cor,Y_cor
10,214.0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,28.5639543,77.2587868
11,173.0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,28.8446874,77.0332666
12,23.1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,28.5206826,76.8023871
13,451.0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,28.744,77.12
14,224.0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,28.6235,77.2494

In [42]:
X_train.head()

,Value,"Location_Anand Vihar, Delhi - DPCC","Location_Ashok Vihar, Delhi - DPCC","Location_Aya Nagar, Delhi - IMD","Location_Bawana, Delhi - DPCC","Location_Burari Crossing, Delhi - IMD","Location_CRRI Mathura Road, Delhi - IMD","Location_Chandni Chowk, Delhi - IITM",Location_Civil Lines,"Location_DTU, Delhi - CPCB",...,"Location_Vivek Vihar, Delhi - DPCC","Location_Wazirpur, Delhi - DPCC",Pollutant_NO2,Pollutant_O3,Pollutant_PM10,Pollutant_PM2.5,Pollutant_SO2,Source Name_StateAir_NewDelhi,Source Name_caaqm,Source Name_data.gov.in
10,214.0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
11,173.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
12,23.1,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
13,451.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
14,224.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [43]:
y_train_for_X_cor = df2.X_cor
y_train_for_Y_cor = df2.Y_cor

In [44]:
X_test = df1.drop(['Coordinates'],axis=1)
#test dataset

In [45]:
X_test.head()

,Value,"Location_Anand Vihar, Delhi - DPCC","Location_Ashok Vihar, Delhi - DPCC","Location_Aya Nagar, Delhi - IMD","Location_Bawana, Delhi - DPCC","Location_Burari Crossing, Delhi - IMD","Location_CRRI Mathura Road, Delhi - IMD","Location_Chandni Chowk, Delhi - IITM",Location_Civil Lines,"Location_DTU, Delhi - CPCB",...,"Location_Vivek Vihar, Delhi - DPCC","Location_Wazirpur, Delhi - DPCC",Pollutant_NO2,Pollutant_O3,Pollutant_PM10,Pollutant_PM2.5,Pollutant_SO2,Source Name_StateAir_NewDelhi,Source Name_caaqm,Source Name_data.gov.in
0,5.0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
1,183.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
2,53.0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
3,5.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
4,25.0,0,0,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1

In [46]:
X_test.shape

(254, 64)

In [47]:
from sklearn.pipeline import make_pipeline

In [48]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression

In [49]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LinearRegression
from sklearn.gaussian_process import GaussianProcessRegressor

# MODEL HYPERTUNNIG
implementing hypertunning for Random forest, Linear regresion

In [50]:
model_prams = {
    'RFR' :{
        'model' : RandomForestRegressor(),
        'pram' : {'n_estimators' :[1,5,10]
    }
    },
    'LR' :{
        'model' : LogisticRegression(solver='liblinear',multi_class='auto'),
        'pram' :{
            'C': [1,5,10]
        }
    },
   
    
}

In [51]:
from sklearn.model_selection import GridSearchCV
score =[]

for model_name, model_pram in model_prams.items():
    clf = GridSearchCV(model_pram['model'], model_pram['pram'], cv = 5)
    clf.fit(X_train, y_train_for_Y_cor)
    score.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })

C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(

In [52]:
df_hypertunnig = pd.DataFrame(score, columns = ['model','best_score','best_params'])

Model hypertunning parameter

In [53]:
df_hypertunnig.head()

  model  best_score           best_params
0   RFR    0.829368  {'n_estimators': 10}
1    LR    0.468293             {'C': 10}

In [54]:
regr = RandomForestRegressor(random_state=0, n_estimators = 5)

for x cordinates

In [55]:
regr.fit(X_train,y_train_for_X_cor)

RandomForestRegressor(n_estimators=5, random_state=0)

In [56]:
regr.predict(X_test)

array([28.530785  , 28.6909732 , 28.61201402, 28.53458286, 28.4706914 ,
       28.69896224, 28.5512005 , 28.5648    , 28.6517    , 28.6517    ,
       28.66490074, 28.5918245 , 28.66525452, 28.73002692, 28.6266776 ,
       28.73261   , 28.647792  , 28.61152534, 28.54644624, 28.73419604,
       28.7500499 , 28.6604504 , 28.531346  , 28.7509516 , 28.82720628,
       28.6281349 , 28.56710286, 28.5512005 , 28.7500499 , 28.65778   ,
       28.8446874 , 28.73002692, 28.73743456, 28.6533834 , 28.56715992,
       28.6674928 , 28.72723384, 28.72723384, 28.61176968, 28.653044  ,
       28.6956842 , 28.5627763 , 28.6341    , 28.531346  , 28.5918245 ,
       28.68146112, 28.6957202 , 28.6298522 , 28.588333  , 28.588333  ,
       28.6568812 , 28.5504249 , 28.69582396, 28.4994994 , 28.6272877 ,
       28.73743456, 28.61633348, 28.6304663 , 28.6956842 , 28.531346  ,
       28.70806584, 28.4990352 , 28.5710274 , 28.4706914 , 28.7762    ,
       28.5512005 , 28.5512005 , 28.67178144, 28.65698884, 28.667396  ,
       28.531346  , 28.659961  , 28.6669772 , 28.83157656, 28.67265312,
       28.53195622, 28.66490074, 28.7125858 , 28.4994994 , 28.670598  ,
       28.6957202 , 28.68216754, 28.56474144, 28.5108561 , 28.66643694,
       28.7762    , 28.7500499 , 28.66286144, 28.65560916, 28.591     ,
       28.591     , 28.531346  , 28.69813224, 28.70194872, 28.6978668 ,
       28.69292832, 28.69286048, 28.53312744, 28.53312744, 28.7033174 ,
       28.55830962, 28.65640872, 28.669449  , 28.6125027 , 28.61185113,
       28.4706914 , 28.4706914 , 28.69858996, 28.654008  , 28.659961  ,
       28.659961  , 28.83594684, 28.53195622, 28.73907008, 28.7001576 ,
       28.58233624, 28.69380758, 28.6222596 , 28.5504249 , 28.69565236,
       28.73907008, 28.66907914, 28.5648    , 28.6571    , 28.5504249 ,
       28.6277535 , 28.6924688 , 28.647792  , 28.7190462 , 28.69734994,
       28.664328  , 28.6711576 , 28.70194872, 28.58182218, 28.6222596 ,
       28.6341    , 28.6341    , 28.591     , 28.5648    , 28.5512005 ,
       28.5981596 , 28.6648174 , 28.72579212, 28.6659652 , 28.71617008,
       28.699394  , 28.7762    , 28.7500499 , 28.6341    , 28.65270118,
       28.591     , 28.591     , 28.69522334, 28.657843  , 28.73579904,
       28.732528  , 28.55088948, 28.56552858, 28.663329  , 28.4988031 ,
       28.6281349 , 28.701616  , 28.58079406, 28.65305712, 28.591     ,
       28.5648    , 28.4706914 , 28.54082052, 28.7762    , 28.66767738,
       28.6748944 , 28.83594684, 28.6974848 , 28.53075156, 28.6471564 ,
       28.7012514 , 28.5828503 , 28.7762    , 28.7500499 , 28.6292381 ,
       28.6292381 , 28.6309474 , 28.588333  , 28.6176547 , 28.6341    ,
       28.5512005 , 28.72863038, 28.6501644 , 28.58079406, 28.7259592 ,
       28.7500499 , 28.5627763 , 28.650617  , 28.64542   , 28.6555356 ,
       28.69316776, 28.7040138 , 28.4706914 , 28.4706914 , 28.4994994 ,
       28.4990352 , 28.67150412, 28.65304   , 28.7005222 , 28.7762    ,
       28.5512005 , 28.6673616 , 28.5504249 , 28.72723384, 28.56552858,
       28.4706914 , 28.670642  , 28.6517    , 28.531346  , 28.69169684,
       28.4706914 , 28.6176547 , 28.6956842 , 28.58182218, 28.588333  ,
       28.588333  , 28.65800084, 28.5648    , 28.70161844, 28.5366411 ,
       28.54082052, 28.653372  , 28.56552858, 28.54644624, 28.5627763 ,
       28.5918245 , 28.699497  , 28.65358   , 28.5512005 , 28.7070714 ,
       28.83157656, 28.54082052, 28.56631572, 28.5627763 , 28.5627763 ,
       28.588333  , 28.6442156 , 28.65187646, 28.5512005 , 28.70088086,
       28.6292108 , 28.723994  , 28.570173  , 28.6304663 , 28.5918245 ,
       28.66806726, 28.5648    , 28.69828224, 28.69463292])

for y cordinates

In [57]:
model1 = regr.fit(X_train,y_train_for_Y_cor)

In [58]:
model1.predict(X_test)

array([77.271255  , 77.264156  , 77.23355724, 76.79914168, 77.1099364 ,
       77.21049346, 77.25895896, 77.1744    , 77.1581    , 77.17137   ,
       77.21187262, 77.22673592, 77.1167    , 77.2043886 , 77.28617412,
       77.260725  , 77.3153218 , 77.22978268, 76.84401512, 77.20570346,
       77.1112615 , 77.21187262, 77.2157224 , 77.19758462, 77.07449524,
       77.28565668, 77.24695636, 77.25895896, 77.1112615 , 77.16658   ,
       77.0332666 , 77.20589922, 77.08261752, 77.20479582, 77.21455262,
       77.31396292, 77.20110922, 77.20589922, 77.22079496, 77.2070947 ,
       77.19887406, 77.12602424, 77.2005    , 77.2024524 , 77.22673592,
       77.31439528, 77.21217788, 77.24108948, 77.2222236 , 77.2222236 ,
       77.1486296 , 77.20607262, 77.210362  , 77.24353202, 77.28617412,
       77.08261752, 77.22876724, 77.24108948, 77.19887406, 77.2035032 ,
       77.21533292, 77.25198534, 77.0719006 , 77.1099364 , 77.051074  ,
       77.26374896, 77.26374896, 77.28690872, 77.19828788, 77.1486296 ,
       77.2157224 , 77.21187262, 77.31526   , 77.07449524, 77.1167    ,
       77.27029574, 77.21187262, 77.19758462, 77.25680202, 77.1167    ,
       77.20746194, 77.273995  , 77.24547508, 76.7093948 , 77.21316206,
       77.051074  , 77.1112615 , 77.28690872, 77.28211872, 77.05      ,
       77.05      , 77.2157224 , 77.21999146, 77.210362  , 77.187594  ,
       77.21217788, 77.199056  , 77.26933648, 77.26933648, 77.239688  ,
       76.88888856, 77.31353056, 77.1167    , 77.23304952, 77.22079496,
       77.1099364 , 77.1099364 , 77.28211872, 77.1571096 , 77.21187262,
       77.21187262, 77.04700948, 77.27029574, 77.07018336, 77.2055982 ,
       77.23096248, 77.28690872, 77.20603564, 77.21934262, 77.21225194,
       77.07018336, 77.076574  , 77.17114   , 77.17137   , 77.21934262,
       77.28617412, 77.254317  , 77.3153664 , 77.20111966, 77.076574  ,
       77.21187262, 77.21187262, 77.210362  , 77.23129272, 77.21346592,
       77.2005    , 77.191002  , 77.05      , 77.17114   , 77.26374896,
       77.20708644, 77.21187262, 77.1993376 , 77.31526   , 77.20746194,
       77.1975118 , 77.051074  , 77.1112615 , 77.2005    , 77.20307788,
       77.05      , 77.05      , 77.200864  , 77.31482764, 77.09505168,
       77.11992   , 76.9640952 , 77.24382072, 77.20237462, 77.256762  ,
       77.28565668, 77.2055982 , 77.21835296, 77.20307788, 77.05      ,
       77.1744    , 77.1099364 , 76.9101925 , 77.051074  , 77.28690872,
       77.076574  , 77.04700948, 77.259366  , 76.8562898 , 77.3153218 ,
       77.1923282 , 77.23063224, 77.051074  , 77.1112615 , 77.23462374,
       77.232948  , 77.23462374, 77.2222236 , 77.20708644, 77.2005    ,
       77.26374896, 77.20110922, 77.3153218 , 77.21835296, 77.210362  ,
       77.1112615 , 77.13929424, 77.1618996 , 77.1618996 , 77.1618996 ,
       77.210362  , 77.1983196 , 77.1099364 , 77.1099364 , 77.25680202,
       77.25680202, 77.1167    , 77.3152    , 77.2010512 , 77.051074  ,
       77.25895896, 77.076574  , 77.21455262, 77.19909524, 77.24382072,
       77.1099364 , 77.21187262, 77.17137   , 77.2024524 , 77.1993376 ,
       77.1099364 , 77.20708644, 77.19887406, 77.22617248, 77.2222236 ,
       77.2222236 , 77.20307788, 77.1744    , 77.21999146, 77.2664587 ,
       76.9101925 , 77.3153664 , 77.24861072, 76.84401512, 77.13929424,
       77.22673592, 77.076574  , 77.16658   , 77.25895896, 77.1983196 ,
       77.06075236, 76.9101925 , 77.23534072, 77.13450424, 77.13929424,
       77.2174336 , 77.2005    , 77.20307788, 77.25895896, 77.1167    ,
       77.28565668, 77.2055982 , 76.933762  , 77.22614374, 77.22673592,
       77.076574  , 77.1744    , 77.21999146, 77.19887406])

# for linear regression

In [59]:
from sklearn.linear_model import LinearRegression
LR = LinearRegression()

In [60]:
LR.fit(X_train,y_train_for_X_cor)

LinearRegression()

In [61]:
LR.predict(X_test)        # x cordinate

array([ 2.85312532e+01,  2.86916181e+01,  2.86092254e+01,  2.85381819e+01,
        2.84683399e+01,  2.87232935e+01,  2.85489472e+01,  2.85546247e+01,
        2.86503118e+01,  2.86504353e+01,  2.88129890e+01,  2.85894729e+01,
        2.86624544e+01,  2.87270050e+01,  2.86250432e+01,  2.86916371e+01,
        2.86468426e+01,  2.86093441e+01,  2.85382019e+01,  2.87123133e+01,
        2.87477244e+01,  2.88129791e+01,  2.85291150e+01, -5.73192186e+04,
        2.88315699e+01,  2.86250653e+01,  2.85635069e+01,  2.85390342e+01,
        2.87478258e+01,  2.86503084e+01,  2.88315510e+01,  2.87269869e+01,
        2.87341780e+01,  2.88129695e+01,  2.85333192e+01,  2.86684841e+01,
        2.87269798e+01,  2.87269840e+01,  2.86092434e+01,  2.88130935e+01,
        2.88076246e+01,  2.85604129e+01,  2.86340471e+01,  2.85290087e+01,
        2.85894748e+01,  2.86685045e+01,  2.86930987e+01,  2.86278148e+01,
        2.85859529e+01,  2.85859546e+01,  2.86372955e+01,  2.85481118e+01,
        2.88129801e+01,  2.84973120e+01,  2.86156725e+01,  2.87342971e+01,
        2.86024963e+01,  2.86278090e+01,  2.88072011e+01,  2.85232142e+01,
        2.87233372e+01,  2.84917297e+01,  2.85434116e+01,  2.84683528e+01,
        2.87738618e+01,  2.85488500e+01,  2.85488365e+01,  2.86788190e+01,
        2.86424497e+01,  2.86373161e+01,  2.85289928e+01,  2.88131006e+01,
        2.86684806e+01,  2.88315550e+01,  2.86682229e+01,  2.85313522e+01,
        2.88129887e+01,  2.88129569e+01,  2.84972937e+01,  2.86682262e+01,
        2.86932188e+01,  2.86916165e+01,  2.85636287e+01,  2.85381866e+01,
        2.88129740e+01,  2.87738486e+01,  2.87477104e+01,  2.86788198e+01,
        2.86789425e+01,  2.85995873e+01,  2.85995504e+01,  2.85289931e+01,
        2.87234078e+01,  2.88129814e+01, -4.04599387e+05,  2.86930955e+01,
        2.86931170e+01,  2.85312304e+01,  2.85312345e+01,  2.86823498e+01,
        2.85383080e+01,  2.86686021e+01,  2.86682301e+01,  2.86092236e+01,
        2.86092231e+01,  2.84683412e+01,  2.84640427e+01,  2.86712474e+01,
        2.86314161e+01,  2.88131023e+01,  2.88131036e+01,  2.88316711e+01,
        2.85240828e+01,  2.87341843e+01,  2.86983238e+01,  2.85794151e+01,
        2.86788399e+01,  2.85894891e+01,  2.85481047e+01,  2.86930913e+01,
        2.87341757e+01,  2.86823083e+01,  2.85629393e+01,  2.86503108e+01,
        2.85480893e+01,  2.86251654e+01,  2.86916191e+01,  2.86468648e+01,
        2.86917052e+01,  2.86823268e+01, -5.73192185e+04,  1.20663474e+05,
        2.88129813e+01,  2.85792878e+01,  2.85894763e+01,  2.86341757e+01,
        2.86340680e+01,  2.85995672e+01,  2.85629596e+01,  2.85488361e+01,
        2.85895833e+01,  2.88129836e+01, -4.04599387e+05,  2.86655690e+01,
        2.86845710e+01,  2.88129954e+01,  2.87738381e+01,  2.87477035e+01,
        2.86340508e+01,  2.86552298e+01,  2.85996825e+01,  2.85963353e+01,
        2.88129929e+01,  2.86684891e+01,  2.87341985e+01,  2.87277694e+01,
        2.85433949e+01,  2.85583701e+01,  1.20663474e+05,  2.84972908e+01,
        2.86250505e+01,  2.86983253e+01,  2.85792881e+01,  2.86553360e+01,
        2.85995706e+01,  2.85629372e+01,  2.84683420e+01,  2.85342297e+01,
        2.87738419e+01,  2.86788188e+01,  2.86823102e+01,  2.88315489e+01,
        2.86917378e+01,  2.85435043e+01,  2.86468426e+01,  2.86983455e+01,
        2.85792914e+01,  2.87666921e+01,  2.87477019e+01,  2.86278044e+01,
        2.86279338e+01,  2.86219316e+01,  2.85859525e+01,  2.85836949e+01,
        2.86258401e+01,  2.85488292e+01,  2.87181418e+01,  2.86469613e+01,
        2.85793083e+01,  2.88129779e+01,  2.87417185e+01,  2.85605207e+01,
        2.86373037e+01,  2.86374216e+01,  2.86372971e+01, -5.73192186e+04,
        2.88129804e+01,  2.84684548e+01,  2.84683390e+01,  2.84972879e+01,
        2.84974147e+01,  2.86683472e+01,  2.86381079e+01,  2.86984460e+01,
        2.87739575e+01,  2.85488250e+01,  2.86823038e+01,  2.85482122e+01,
        2.87271040e+01,  2.85635034e+01,  2.84684639e+01,  2.88129729e+01,
        2.86503315e+01,  2.85289880e+01, -5.73192185e+04,  2.84683403e+01,
        2.85892233e+01,  2.88127284e+01,  2.85677979e+01,  2.85859725e+01,
        2.85860855e+01,  2.86552139e+01,  2.85630616e+01,  2.87232785e+01,
        2.85312323e+01,  2.85433896e+01,  2.86468425e+01,  2.85635071e+01,
        2.85343133e+01,  2.85603921e+01,  2.85894746e+01,  2.86751587e+01,
        2.86423151e+01,  2.85488163e+01,  2.88130628e+01,  2.88255659e+01,
        2.85433915e+01,  2.85635290e+01,  2.85497493e+01,  2.85603902e+01,
        2.85792268e+01,  2.86340494e+01,  2.86552147e+01,  2.85489357e+01,
        2.86682483e+01,  2.86250420e+01,  2.86983299e+01,  2.85381869e+01,
        2.86278310e+01,  2.85895944e+01,  2.86824196e+01,  2.85629417e+01,
        2.87232865e+01,  2.88129328e+01])

In [62]:
model2 = LR.fit(X_train,y_train_for_Y_cor)

In [63]:
model2.predict(X_test)   # y cordinate

array([    77.26756224,     77.27312664,     77.2354329 ,     76.82044837,
           77.10877849,     77.2000288 ,     77.27222554,     77.22835203,
           77.15148884,     77.15116561,     77.15179999,     77.22615022,
           77.15886679,     77.16434465,     77.28481197,     77.27301355,
           77.31494949,     77.2351235 ,     76.8203441 ,     77.26396358,
           77.10996478,     77.15185776,     77.18869263,   9714.38403868,
           77.06641993,     77.28469598,     77.25361599,     77.32956251,
           77.10975816,     77.15152293,     77.0665324 ,     77.16445236,
           77.08747784,     77.15191386,     77.30070286,     77.31293056,
           77.1644935 ,     77.16445448,     77.23532581,     77.15157318,
           77.18303262,     77.11691421,     77.20004628,     77.18892823,
           77.22613875,     77.31282382,     77.18041641,     77.24410046,
           77.22067574,     77.22068085,     77.14509276,     77.21456894,
           77.15185156,     77.26357744,     77.33938763,     77.0871805 ,
           77.27461226,     77.24411983,     77.18549844,     77.22266721,
           77.19977215,     77.29608042,     76.93590552,     77.10870099,
           77.04983642,     77.2724075 ,     77.2724887 ,     77.30139823,
           77.23064893,     77.1449854 ,     77.189023  ,     77.15153176,
           77.31296527,     77.06650852,     77.1252816 ,     77.26736918,
           77.15180167,     77.15198715,     77.26368622,     77.12524751,
           77.18009854,     77.27312153,     77.25328809,     76.82043562,
           77.15187299,     77.04991515,     77.11004845,     77.30139375,
           77.30106109,     77.03983767,     77.04005495,     77.18902098,
           77.19974662,     77.15184412,  68074.18261146,     77.18043506,
           77.18030763,     77.26769708,     77.26767349,     77.32709121,
           76.82011035,     77.31263939,     77.12523923,     77.23544383,
           77.23543194,     77.10877093,     77.13379665,     77.34548334,
           77.17933836,     77.15152202,     77.15151393,     77.06621453,
           77.30931266,     77.08745538,     77.16387351,     77.23156469,
           77.3012745 ,     77.22605339,     77.21461237,     77.18044519,
           77.08750576,     77.07552243,     77.17992612,     77.15150892,
           77.21470237,     77.28449675,     77.27312064,     77.3148179 ,
           77.20240884,     77.07542678,   9714.38358676, -20195.2827934 ,
           77.15184469,     77.23192464,     77.22613028,     77.19969346,
           77.19993707,     77.03994257,     77.17982061,     77.27249079,
           77.22588892,     77.15183155,  68074.18268341,     77.32991543,
           77.23006826,     77.1517607 ,     77.04997663,     77.11007399,
           77.20003968,     77.15623319,     77.03966742,     77.05877187,
           77.15177488,     77.3129155 ,     77.08737048,     77.1248051 ,
           76.93600522,     77.28352325, -20195.28288072,     77.2636885 ,
           77.28478396,     77.16385052,     77.23190827,     77.15599882,
           77.03993737,     77.17995343,     77.10876243,     76.9893692 ,
           77.04994007,     77.30138494,     77.07552586,     77.06652975,
           77.27281124,     76.93574945,     77.31493451,     77.16374501,
           77.23190352,     77.09158314,     77.11009822,     77.24416132,
           77.24378921,     77.27835434,     77.22069273,     77.25979052,
           77.24784587,     77.27253123,     77.21595218,     77.31463963,
           77.23180276,     77.15186471,     77.14493482,     77.1166706 ,
           77.14505966,     77.14475473,     77.14509804,   9714.38394529,
           77.15184618,     77.10849071,     77.10878403,     77.26371967,
           77.2633628 ,     77.12493907,     77.36580651,     77.16354331,
           77.04966308,     77.27255573,     77.0755633 ,     77.21436786,
           77.16415159,     77.25363616,     77.10843765,     77.15189368,
           77.15138642,     77.18903621,   9714.38307376,     77.1087761 ,
           77.22759925,     77.15331334,     77.29882535,     77.22057393,
           77.22030011,     77.1563284 ,     77.17961028,     77.20011779,
           77.26767145,     76.93603588,     77.31494965,     77.25360022,
           76.84298565,     77.11703778,     77.22613998,     77.11716426,
           77.19806293,     77.27260209,     77.15175164,     77.10137886,
           76.93601042,     77.25348485,     77.17900578,     77.11704904,
           77.25985175,     77.20004786,     77.15632363,     77.27229266,
           77.12513152,     77.28483373,     77.16383792,     76.82043393,
           77.24400446,     77.22582396,     77.07527009,     77.17992708,
           77.20007163,     77.15212358])

# From GaussianProcessRegressor

In [64]:
from sklearn.gaussian_process import GaussianProcessRegressor

In [65]:
gpr = GaussianProcessRegressor(random_state=0)

In [66]:
gpr.fit(X_train,y_train_for_X_cor)

GaussianProcessRegressor(random_state=0)

In [67]:
gpr.predict(X_test)             # x cordinate

array([1.11346569e+001, 6.54231943e+000, 2.60049141e+000, 8.79540371e+000,
       1.04851100e+001, 1.00472999e+001, 1.44430211e+000, 0.00000000e+000,
       1.72267672e+001, 1.89752140e+000, 7.63785236e+000, 5.79322478e+000,
       0.00000000e+000, 9.18542779e+000, 5.36336253e+000, 8.64225227e+000,
       8.30232273e+000, 1.70028618e+000, 1.37877330e+001, 0.00000000e+000,
       1.10473446e+001, 5.09167704e+000, 3.47549052e-001, 1.05336633e+001,
       3.61024728e+000, 9.68079753e+000, 4.82297198e+000, 0.00000000e+000,
       6.40456015e+000, 2.60868434e+000, 3.48268848e-002, 5.87204951e+000,
       1.14613428e+001, 1.61260226e+000, 0.00000000e+000, 1.10268526e+001,
       2.38887493e+000, 4.00940554e+000, 1.41154468e+001, 1.42221028e+000,
       0.00000000e+000, 1.14726927e+001, 5.53725998e+000, 1.16856119e+001,
       1.26519885e+001, 1.00332491e+001, 9.50334607e-001, 2.86264505e+000,
       1.20693297e+001, 2.96121630e+000, 1.10207021e+001, 8.01445993e+000,
       9.93113280e+000, 9.56170664e+000, 0.00000000e+000, 1.82714998e-001,
       0.00000000e+000, 6.37744332e+000, 0.00000000e+000, 0.00000000e+000,
       1.23122727e-021, 0.00000000e+000, 1.16820716e+001, 3.61858034e+000,
       1.00461735e+001, 7.62332134e+000, 8.32528770e+000, 5.13616410e+000,
       0.00000000e+000, 9.39298060e+000, 9.89733956e+000, 1.55288077e+000,
       2.60868434e+000, 2.86268750e+000, 2.38163602e+000, 1.92865322e-001,
       1.44398384e+001, 2.41746292e-001, 3.10156105e+000, 4.63040339e+000,
       2.00916197e+000, 7.74783184e+000, 5.37601481e+000, 4.04741645e-003,
       1.84381296e+001, 5.82827311e+000, 7.83160638e+000, 4.51997464e+000,
       2.11555258e+000, 9.12531652e+000, 2.59749533e-002, 4.04741645e-003,
       2.00512926e+000, 1.00799731e+001, 1.63433528e+001, 5.13609096e+000,
       1.00461735e+001, 1.57937092e+000, 2.47848152e-001, 0.00000000e+000,
       3.07995581e-001, 5.01046080e-001, 2.06555854e+000, 9.11517775e-001,
       1.02751764e+001, 4.19952836e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 2.76953020e+000, 2.15465347e+000, 8.65381765e-001,
       0.00000000e+000, 7.36826051e+000, 3.56600227e+000, 1.44533437e+000,
       8.94710589e+000, 1.10651628e+001, 3.91244713e+000, 3.49525759e+000,
       4.29502765e+000, 1.25203428e+001, 1.33484262e+001, 7.31119298e+000,
       1.78955244e+000, 2.35059998e+000, 2.06518586e+000, 1.09508446e+001,
       0.00000000e+000, 5.41849262e+000, 6.77235042e+000, 1.13314937e+001,
       1.07152616e+001, 2.80514645e+000, 9.95754221e+000, 4.01617650e-001,
       1.09553261e+001, 1.46011838e+001, 9.39383267e+000, 1.34596209e+001,
       1.44559198e-001, 6.62162970e+000, 1.07445626e+001, 0.00000000e+000,
       0.00000000e+000, 2.26427864e+001, 2.25040069e+000, 1.39632021e+001,
       4.00278027e+000, 8.38812811e+000, 7.67258114e+000, 0.00000000e+000,
       5.41849262e+000, 9.89733956e+000, 9.72960798e+000, 0.00000000e+000,
       3.57033924e+000, 0.00000000e+000, 3.79079281e+000, 1.06061806e+001,
       9.89733956e+000, 7.74796559e+000, 1.33891320e+001, 1.91886140e+000,
       4.48827775e+000, 2.79922038e+000, 6.39432610e+000, 0.00000000e+000,
       1.10206932e+001, 6.38234788e+000, 7.37626498e+000, 5.36336465e+000,
       1.89928335e+000, 5.67179078e+000, 4.05274542e+000, 9.44955954e+000,
       7.67242962e-001, 0.00000000e+000, 2.79924456e+000, 3.87380771e+000,
       9.88896941e-001, 0.00000000e+000, 1.37765556e+000, 0.00000000e+000,
       0.00000000e+000, 1.04449551e+001, 0.00000000e+000, 4.96042183e+000,
       1.30734511e+001, 9.64752900e+000, 0.00000000e+000, 2.32883768e+000,
       1.29004927e-004, 3.17090821e-001, 5.22001529e+000, 1.39900786e+001,
       2.34290154e-021, 2.14278462e+000, 1.28346415e+001, 7.28839487e-002,
       3.05426538e+000, 1.03001867e-005, 0.00000000e+000, 5.37601481e+000,
       6.71739899e+000, 1.66506386e+000, 1.08783176e+001, 1.30168172e+000,
       4.76109001e+000, 4.26508226e+000, 1.26539786e+000, 7.77118955e+000,
       1.17662700e+001, 1.23816362e+001, 2.02113425e+001, 1.21380988e+001,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 8.21235534e+000,
       1.52960324e+000, 5.66919775e+000, 1.65211569e+000, 1.85175541e+001,
       1.11987918e+001, 2.52331484e+000, 3.16327358e+000, 5.59826778e+000,
       0.00000000e+000, 5.25130510e+000, 5.42722065e-001, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 5.33667797e-312, 0.00000000e+000,
       1.02764361e+001, 1.13959996e+001, 0.00000000e+000, 2.92677985e+000,
       0.00000000e+000, 3.60563860e+000, 1.09302387e+001, 4.63908721e-002,
       1.01149525e+001, 2.60868434e+000, 1.09302387e+001, 7.47260401e+000,
       1.23302290e+001, 1.11967073e+000, 6.03906011e+000, 5.88295834e+000,
       3.69583744e+000, 0.00000000e+000])

In [68]:
model3 = gpr.fit(X_train,y_train_for_Y_cor)

In [69]:
model3.predict(X_test)             # y cordinate

array([3.00531920e+001, 1.75996016e+001, 6.99942873e+000, 2.37205826e+001,
       2.83978462e+001, 2.71078239e+001, 3.89426021e+000, 0.00000000e+000,
       4.63896851e+001, 5.11222549e+000, 2.06249998e+001, 1.56483807e+001,
       0.00000000e+000, 2.47153730e+001, 1.44463764e+001, 2.31996472e+001,
       2.24196562e+001, 4.57894453e+000, 3.71205707e+001, 0.00000000e+000,
       2.97005281e+001, 1.37475064e+001, 9.35032886e-001, 2.82045695e+001,
       9.71776056e+000, 2.60968066e+001, 1.29866422e+001, 0.00000000e+000,
       1.72721747e+001, 7.04458659e+000, 9.38548507e-002, 1.57532093e+001,
       3.08764925e+001, 4.36365666e+000, 0.00000000e+000, 2.97208747e+001,
       6.43815603e+000, 1.08201093e+001, 3.80362940e+001, 3.85150485e+000,
       0.00000000e+000, 3.09504957e+001, 1.49604692e+001, 3.14604457e+001,
       3.41047443e+001, 2.70692254e+001, 2.56966853e+000, 7.69769710e+000,
       3.25104496e+001, 7.98605005e+000, 2.97043698e+001, 2.15289243e+001,
       2.68229818e+001, 2.57819052e+001, 0.00000000e+000, 4.94922268e-001,
       0.00000000e+000, 1.72298454e+001, 0.00000000e+000, 0.00000000e+000,
       3.31518988e-021, 0.00000000e+000, 3.14364025e+001, 9.74065673e+000,
       2.70846564e+001, 2.05325294e+001, 2.24632656e+001, 1.38538560e+001,
       0.00000000e+000, 2.52723917e+001, 2.67074169e+001, 4.18540321e+000,
       7.04458659e+000, 7.69780983e+000, 6.42885170e+000, 5.20756912e-001,
       3.89532518e+001, 6.53427028e-001, 8.29641534e+000, 1.25313859e+001,
       5.39543104e+000, 2.08238551e+001, 1.44841917e+001, 1.09050684e-002,
       4.97690343e+001, 1.57005845e+001, 2.11317684e+001, 1.22074146e+001,
       5.68960612e+000, 2.46128685e+001, 7.00998226e-002, 1.09050684e-002,
       5.38570259e+000, 2.71433625e+001, 4.40610796e+001, 1.38536585e+001,
       2.70846564e+001, 4.22845012e+000, 6.66629789e-001, 0.00000000e+000,
       8.30295167e-001, 1.35332876e+000, 5.57676293e+000, 2.45225168e+000,
       2.76241563e+001, 1.12886201e+001, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 7.46280032e+000, 5.79719169e+000, 2.33662009e+000,
       0.00000000e+000, 1.98448980e+001, 9.61656338e+000, 3.89609225e+000,
       2.41330567e+001, 2.97489009e+001, 1.05270816e+001, 9.39692145e+000,
       1.15240633e+001, 3.37180064e+001, 3.60096512e+001, 1.97513742e+001,
       4.82715202e+000, 6.34686746e+000, 5.57576103e+000, 2.95483184e+001,
       0.00000000e+000, 1.46202620e+001, 1.82417046e+001, 3.04951823e+001,
       2.88958867e+001, 7.56101078e+000, 2.68889880e+001, 1.08227489e+000,
       2.95032112e+001, 3.93285991e+001, 2.52748732e+001, 3.63972962e+001,
       3.89679787e-001, 1.77709509e+001, 2.89640002e+001, 0.00000000e+000,
       0.00000000e+000, 6.09606449e+001, 6.06625852e+000, 3.75208780e+001,
       1.06917142e+001, 2.25991407e+001, 2.06481437e+001, 0.00000000e+000,
       1.46202620e+001, 2.67074169e+001, 2.62232664e+001, 0.00000000e+000,
       9.62755632e+000, 0.00000000e+000, 1.02352443e+001, 2.86126719e+001,
       2.67074169e+001, 2.08242134e+001, 3.61359717e+001, 5.18285436e+000,
       1.21044611e+001, 7.55586436e+000, 1.72163984e+001, 0.00000000e+000,
       2.97043459e+001, 1.72765719e+001, 1.98734942e+001, 1.44463820e+001,
       5.13186457e+000, 1.52668233e+001, 1.08829405e+001, 2.54682053e+001,
       2.06956432e+000, 0.00000000e+000, 7.55592921e+000, 1.04596934e+001,
       2.67015037e+000, 0.00000000e+000, 3.71854815e+000, 0.00000000e+000,
       0.00000000e+000, 2.81359111e+001, 0.00000000e+000, 1.33703084e+001,
       3.52877861e+001, 2.59926266e+001, 0.00000000e+000, 6.29909740e+000,
       3.47698010e-004, 8.54547973e-001, 1.40391942e+001, 3.77225919e+001,
       6.30731066e-021, 5.79480263e+000, 3.45907270e+001, 1.95797758e-001,
       8.24776163e+000, 2.78550324e-005, 0.00000000e+000, 1.44841917e+001,
       1.80688461e+001, 4.49663755e+000, 2.92343538e+001, 3.51921663e+000,
       1.28423181e+001, 1.15072389e+001, 3.41328778e+000, 2.09614818e+001,
       3.16761073e+001, 3.33657178e+001, 5.44268464e+001, 3.26917073e+001,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 2.21270213e+001,
       4.11984390e+000, 1.52921174e+001, 4.44949815e+000, 4.98109212e+001,
       3.01587538e+001, 6.79862812e+000, 8.49101444e+000, 1.51180439e+001,
       0.00000000e+000, 1.41846811e+001, 1.46298726e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 1.44087520e-311, 0.00000000e+000,
       2.76275271e+001, 3.06544923e+001, 0.00000000e+000, 7.87887090e+000,
       0.00000000e+000, 9.76277278e+000, 2.93835784e+001, 1.24505369e-001,
       2.71523777e+001, 7.04458659e+000, 2.93835784e+001, 2.01392039e+001,
       3.32640070e+001, 3.01796470e+000, 1.62867432e+001, 1.58411571e+001,
       9.98415325e+000, 0.00000000e+000])